/* The following code was generated by JFlex 1.4.3 on 11/19/18 12:06 PM */

/***************************/
/* FILE NAME: LEX_FILE.lex */
/***************************/

/***************************/
/* AUTHOR: OREN ISH SHALOM */
/***************************/

/*************/
/* USER CODE */
/*************/
   
import java_cup.runtime.*;



/******************************/
/* DOLAR DOLAR - DON'T TOUCH! */
/******************************/
      

class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 4;
  public static final int ONELINECOMMENT = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\7\1\2\1\0\1\6\1\1\22\0\1\7\1\4\1\32"+
    "\5\0\1\50\1\51\1\3\1\34\1\52\1\35\1\43\1\33\1\11"+
    "\1\10\1\54\1\53\2\10\1\55\1\56\1\57\1\10\1\45\1\44"+
    "\1\37\1\36\1\40\1\4\1\0\32\5\1\41\1\0\1\42\3\0"+
    "\1\12\1\5\1\15\1\24\1\20\1\31\1\5\1\27\1\30\2\5"+
    "\1\16\1\5\1\23\3\5\1\13\1\17\1\22\1\25\1\5\1\26"+
    "\1\21\1\14\1\5\1\46\1\0\1\47\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\2\1\1\2\1\3\2\4\7\3\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\0\1\20\1\21\1\22\1\23\1\24\1\4"+
    "\1\25\3\26\2\27\1\30\7\3\1\31\1\5\1\32"+
    "\1\33\1\34\1\35\1\4\4\3\1\36\1\37\1\3"+
    "\1\4\5\3\1\4\1\40\1\3\1\41\1\3\1\42"+
    "\1\43\1\44\1\3\1\45";

  private static int [] zzUnpackAction() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\140\0\220\0\300\0\60\0\60\0\360"+
    "\0\u0120\0\u0150\0\u0180\0\u01b0\0\u01e0\0\u0210\0\u0240\0\u0270"+
    "\0\u02a0\0\u02d0\0\u0300\0\60\0\60\0\60\0\60\0\60"+
    "\0\60\0\60\0\60\0\60\0\u0330\0\60\0\60\0\60"+
    "\0\60\0\60\0\u0360\0\60\0\u0390\0\u03c0\0\60\0\u03f0"+
    "\0\60\0\u0150\0\u0420\0\u0450\0\u0480\0\u04b0\0\u04e0\0\u0510"+
    "\0\u0540\0\360\0\u0570\0\60\0\60\0\60\0\60\0\u05a0"+
    "\0\u05d0\0\u0600\0\u0630\0\u0660\0\360\0\360\0\u0690\0\u06c0"+
    "\0\u06f0\0\u0720\0\u0750\0\u0780\0\u07b0\0\u07e0\0\360\0\u0810"+
    "\0\360\0\u0840\0\360\0\u0120\0\360\0\u0870\0\360";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\5\1\6\1\7\1\0\1\10\2\6\1\11"+
    "\1\12\1\13\1\14\1\10\1\15\2\10\1\16\2\10"+
    "\1\17\2\10\1\20\1\10\1\21\1\10\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\4\11\60\0\1\44\2\45\1\46\2\45\1\44\23\45"+
    "\1\44\1\47\2\45\3\44\4\45\1\44\4\45\1\44"+
    "\5\45\1\44\1\50\1\51\3\47\1\44\23\47\1\44"+
    "\3\47\3\44\4\47\1\44\4\47\1\44\5\47\2\0"+
    "\1\6\62\0\1\10\2\0\22\10\21\0\5\10\10\0"+
    "\2\11\41\0\5\11\10\0\2\52\41\0\5\52\5\0"+
    "\1\10\2\0\3\10\1\53\16\10\21\0\5\10\5\0"+
    "\1\10\2\0\10\10\1\54\11\10\21\0\5\10\5\0"+
    "\1\10\2\0\6\10\1\55\13\10\21\0\5\10\5\0"+
    "\1\10\2\0\11\10\1\56\10\10\21\0\5\10\5\0"+
    "\1\10\2\0\10\10\1\57\7\10\1\60\1\10\21\0"+
    "\5\10\5\0\1\10\2\0\17\10\1\61\2\10\21\0"+
    "\5\10\5\0\1\10\2\0\21\10\1\62\21\0\5\10"+
    "\5\63\1\22\4\63\20\22\1\64\25\63\3\0\1\65"+
    "\27\0\1\66\62\0\1\67\31\0\2\11\41\0\1\11"+
    "\1\70\3\11\1\0\2\45\1\0\2\45\1\0\23\45"+
    "\2\0\2\45\3\0\4\45\1\0\4\45\1\0\5\45"+
    "\33\0\1\51\26\0\1\51\62\0\1\10\2\0\3\10"+
    "\1\71\16\10\21\0\5\10\5\0\1\10\2\0\12\10"+
    "\1\72\7\10\21\0\5\10\5\0\1\10\2\0\2\10"+
    "\1\73\17\10\21\0\5\10\5\0\1\10\2\0\12\10"+
    "\1\74\7\10\21\0\5\10\5\0\1\10\2\0\16\10"+
    "\1\75\3\10\21\0\5\10\5\0\1\10\2\0\6\10"+
    "\1\76\13\10\21\0\5\10\5\0\1\10\2\0\20\10"+
    "\1\77\1\10\21\0\5\10\32\63\1\0\25\63\10\0"+
    "\2\11\41\0\2\11\1\100\2\11\5\0\1\10\2\0"+
    "\2\10\1\101\17\10\21\0\5\10\5\0\1\10\2\0"+
    "\15\10\1\102\4\10\21\0\5\10\5\0\1\10\2\0"+
    "\7\10\1\103\12\10\21\0\5\10\5\0\1\10\2\0"+
    "\10\10\1\104\11\10\21\0\5\10\5\0\1\10\2\0"+
    "\6\10\1\105\13\10\21\0\5\10\10\0\2\11\41\0"+
    "\3\11\1\106\1\11\5\0\1\10\2\0\4\10\1\107"+
    "\15\10\21\0\5\10\5\0\1\10\2\0\3\10\1\110"+
    "\16\10\21\0\5\10\5\0\1\10\2\0\7\10\1\111"+
    "\12\10\21\0\5\10\5\0\1\10\2\0\13\10\1\112"+
    "\6\10\21\0\5\10\5\0\1\10\2\0\10\10\1\113"+
    "\11\10\21\0\5\10\10\0\2\11\41\0\4\11\1\114"+
    "\5\0\1\10\2\0\13\10\1\115\6\10\21\0\5\10"+
    "\5\0\1\10\2\0\14\10\1\116\5\10\21\0\5\10"+
    "\5\0\1\10\2\0\7\10\1\117\12\10\21\0\5\10";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2208];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\10\2\0\1\1\2\11\14\1\11\11\1\0"+
    "\5\11\1\1\1\11\2\1\1\11\1\1\1\11\12\1"+
    "\4\11\30\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[79];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to beq matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	/*********************************************************************************/
	/* Create a new java_cup.runtime.Symbol with information about the current token */
	/*********************************************************************************/
	private Symbol symbol(int type)               {return new Symbol(type, yyline, yycolumn);}
	private Symbol symbol(int type, Object value) {return new Symbol(type, yyline, yycolumn, value);}

	/*******************************************/
	/* Enable line number extraction from main */
	/*******************************************/
	public int getLine()    { return yyline + 1; } 
	public int getCharPos() { return yycolumn;   } 


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 134) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> beq reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only beq called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should beq done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will beq read again by then next call of the scanning method
   *
   * @param number  the number of characters to beq read again.
   *                This number must not beq greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will beq executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 29: 
          { return symbol(TokenNames.ASSIGN);
          }
        case 38: break;
        case 8: 
          { return symbol(TokenNames.MINUS);
          }
        case 39: break;
        case 31: 
          { return symbol(TokenNames.NIL);
          }
        case 40: break;
        case 36: 
          { return symbol(TokenNames.RETURN);
          }
        case 41: break;
        case 9: 
          { return symbol(TokenNames.EQ);
          }
        case 42: break;
        case 30: 
          { return symbol(TokenNames.NEW);
          }
        case 43: break;
        case 20: 
          { return symbol(TokenNames.COMMA);
          }
        case 44: break;
        case 12: 
          { return symbol(TokenNames.LBRACK);
          }
        case 45: break;
        case 3: 
          { return symbol(TokenNames.ID, new String(yytext()));
          }
        case 46: break;
        case 1: 
          { /* just skip what was found, do nothing */
          }
        case 47: break;
        case 33: 
          { return symbol(TokenNames.CLASS);
          }
        case 48: break;
        case 18: 
          { return symbol(TokenNames.LPAREN);
          }
        case 49: break;
        case 14: 
          { return symbol(TokenNames.DOT);
          }
        case 50: break;
        case 21: 
          { throw new RuntimeException("Invalid comment char");
          }
        case 51: break;
        case 23: 
          { yybegin(YYINITIAL);
          }
        case 52: break;
        case 4: 
          { Integer out = new Integer(yytext());
					if (out < 32768) return symbol(TokenNames.INT, out);
					throw new RuntimeException("Integer Too Large");
          }
        case 53: break;
        case 17: 
          { return symbol(TokenNames.RBRACE);
          }
        case 54: break;
        case 24: 
          { throw new RuntimeException("Malformed integer");
          }
        case 55: break;
        case 27: 
          { yybegin(COMMENT);
          }
        case 56: break;
        case 7: 
          { return symbol(TokenNames.PLUS);
          }
        case 57: break;
        case 15: 
          { return symbol(TokenNames.SEMICOLON);
          }
        case 58: break;
        case 11: 
          { return symbol(TokenNames.GT);
          }
        case 59: break;
        case 6: 
          { return symbol(TokenNames.DIVIDE);
          }
        case 60: break;
        case 10: 
          { return symbol(TokenNames.LT);
          }
        case 61: break;
        case 5: 
          { throw new RuntimeException("Illegal String");
          }
        case 62: break;
        case 32: 
          { return symbol(TokenNames.ARRAY);
          }
        case 63: break;
        case 13: 
          { return symbol(TokenNames.RBRACK);
          }
        case 64: break;
        case 2: 
          { return symbol(TokenNames.TIMES);
          }
        case 65: break;
        case 19: 
          { return symbol(TokenNames.RPAREN);
          }
        case 66: break;
        case 22: 
          { /*skip*/
          }
        case 67: break;
        case 26: 
          { return symbol(TokenNames.STRING, new String(yytext()));
          }
        case 68: break;
        case 34: 
          { return symbol(TokenNames.WHILE);
          }
        case 69: break;
        case 28: 
          { yybegin(ONELINECOMMENT);
          }
        case 70: break;
        case 16: 
          { return symbol(TokenNames.LBRACE);
          }
        case 71: break;
        case 37: 
          { return symbol(TokenNames.EXTENDS);
          }
        case 72: break;
        case 35: 
          { return symbol(TokenNames.MIN_INT);
          }
        case 73: break;
        case 25: 
          { return symbol(TokenNames.IF);
          }
        case 74: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case YYINITIAL: {
              return symbol(TokenNames.EOF);
            }
            case 80: break;
            case COMMENT: {
              throw new RuntimeException("Unterminated comment at end of file");
            }
            case 81: break;
            case ONELINECOMMENT: {
              return symbol(TokenNames.EOF);
            }
            case 82: break;
            default:
              { return new java_cup.runtime.Symbol(TokenNames.EOF); }
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
